language: c
compiler:
  - gcc
install:
  - sudo apt-get update -y 
# - sudo apt-get upgrade -y 
  - sudo apt-get install -y gcc-mingw-w64-x86-64 g++-mingw-w64-x86-64 binutils-mingw-w64-x86-64 mingw-w64-dev
  - sudo apt-get install -y cmake
script:
  - mkdir target
  - cd target
  - cmake .. -DCMAKE_TOOLCHAIN_FILE=../mingw-w64.cmake -DJANSSON_BUILD_DOCS=OFF -DJANSSON_WITHOUT_TESTS=ON -DJANSSON_BUILD_SHARED_LIBS=ON
  - make
  - make install
  - cd ..
before_deploy:
  - cd install
  - zip jansson.zip -r .
deploy:
  provider: releases
  api_key:
    secure: IwNh1YypYP41kGVajxWkN2SGJq1dyHL5TFAlSCOiJqAmIGAkJENarJppJKHnwni23f7rH2wOP1JX+mURMU/YjjD76Jssepp/tCx3anWtjKRbZL7b37DXPOPOJnYJsrUSta4i/FDZgwJgIAPvMvT1ohe5xsjS4g1k3wkcl0ZgcXM=
  file: jansson.zip
  on:
    tags: true
    repo: firepick-delta/jansson
#   branch: mingw-w64
    all_branches: true
